

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/TestDB
    username: root
    password: 1234
  jpa.hibernate.ddl-auto: none
  jpa.show-sql: true
  jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  batch:
    job:
      name: ${job.name:NONE}

logging:
  level:
    org:
      springframework:
        batch: DEBUG

