

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/TestDB
    username: root
    password: 1234
  jpa.hibernate.ddl-auto: create
  jpa.show-sql: true

  batch:
    job:
      name: ${job.name:NONE}

logging:
  level:
    org:
      springframework:
        batch: DEBUG

